In [64]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [8]:
import pandas as pd

In [9]:
df = pd.read_csv("IMDB Dataset.csv", on_bad_lines='skip')

In [10]:
df.shape

(50000, 2)

In [11]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [12]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [13]:
df.drop_duplicates(inplace=True)

In [14]:
df.shape

(49582, 2)

# Pre-processing of data

## 1.Converting to lowercase

In [15]:
df["review"] = df["review"].str.lower()

## 2.Removing URL's

In [16]:
import re # regular expression

#sample text = 'abc is the word , abc" , # abc => zyz
# new_text = re.sub("abc" , "xyz" , sample_text)

In [17]:
def remove_urls(text):
    text = re.sub( r"http\S+" ,"", text) # patter, replacement , string)
    return text

df["review"]= df["review"].apply(remove_urls)

## 3.Remove Punctuations

In [18]:
def remove_punctuations(text):
    text = re.sub( r"[^A-Za-z0-9\s]" ,"", text) # A-Z ,a-z,0-9 will not be there when there is puctuations
    return text

df["review"]= df["review"].apply(remove_punctuations)

## 4.Remove html tags

In [19]:
def remove_html(text):
    text = re.sub( r"<.*?>" ,"", text) # A-Z ,a-z,0-9 will not be there when there is puctuations
    return text

df["review"]= df["review"].apply(remove_html)
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production br br the filmin...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

## 5. Removing the stopwords

In [20]:
import nltk # natural language tokenizer
nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [21]:
from nltk.tokenize import word_tokenize # tokenizes the word
from nltk.corpus import stopwords
# importds the work
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production br br the filmin...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

In [22]:
# sample_text="I like coding in Java"
# tokens = word_tokenize(sample_text)
# tokens


def remove_stopwords(text):
    tokens = word_tokenize(text)
    stop_words = stopwords.words("english")

    for word in tokens:
        if word in stop_words:
            text = text.replace(word, "")
    return text

df["review"] = df["review"].apply(remove_stopwords)

## 6. Performing Stemming

In [23]:
# running -> run , played->play ,

#PorterStemming

from nltk.stem import PorterStemmer

In [25]:
def stemming(text):
    ps = PorterStemmer()
    stemmed_words= []

    tokens = word_tokenize(text)
    for token in tokens:
        stemmed_token = ps.stem(token)
        stemmed_words.append(stemmed_token)

    return  " ".join(stemmed_words)

df["review"] = df["review"].apply(stemming)

In [26]:
df.head()

                                              review sentiment
0  e revew nted wtchg 1 oz epod ll hook y rght ex...  positive
1  wder ltle producti br br film techniqu unssum ...  positive
2  thought th wder wy spend tme o hot summer week...  positive
3  bsclli re fmli lttle boy jke thk re zomb close...  negative
4  petter mtte love time mey vulli stunng film wt...  positive

## 7. Encoding for the target value

In [28]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["sentiment"] = le.fit_transform(df["sentiment"])

In [29]:
y = df["sentiment"]

In [30]:
y

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 49582, dtype: int64

## 8. Vectorization
#### we will use Tf-IDF vectorization model

In [31]:
df.head()

                                              review  sentiment
0  e revew nted wtchg 1 oz epod ll hook y rght ex...          1
1  wder ltle producti br br film techniqu unssum ...          1
2  thought th wder wy spend tme o hot summer week...          1
3  bsclli re fmli lttle boy jke thk re zomb close...          0
4  petter mtte love time mey vulli stunng film wt...          1

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer(max_features=5000)

X = tf.fit_transform(df["review"])

In [37]:
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4057140 stored elements and shape (49582, 5000)>

In [38]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4057140 stored elements and shape (49582, 5000)>
  Coords	Values
  (0, 3538)	0.05515484681268887
  (0, 2868)	0.09361182809242374
  (0, 4940)	0.11467310366614668
  (0, 3002)	0.47200539890110405
  (0, 1275)	0.1357698919196183
  (0, 2289)	0.049500237517476293
  (0, 1933)	0.0791260308382
  (0, 3550)	0.0963974330192639
  (0, 1362)	0.06162489377343992
  (0, 1963)	0.061560444992697486
  (0, 219)	0.08588920995304898
  (0, 1620)	0.0738170550485134
  (0, 4369)	0.041994187696759305
  (0, 4171)	0.17799685402440263
  (0, 3693)	0.033532198172897175
  (0, 4737)	0.26798942924092045
  (0, 3805)	0.04427609784380831
  (0, 4769)	0.05877405881441711
  (0, 1739)	0.037520883911174724
  (0, 4497)	0.07614066339174266
  (0, 3857)	0.17537900435282314
  (0, 1630)	0.06142445471882175
  (0, 1862)	0.07433134577032253
  (0, 3329)	0.06406818508428483
  (0, 3332)	0.0844754682576354
  :	:
  (49581, 4890)	0.10682334916138103
  (49581, 1542)	0.17584072573791829
  (49581, 4494)	0.09410069396961679
  (49581, 434)	0.11251655954741112
  (49581, 4277)	0.10905956327445408
  (49581, 1958)	0.0999074542943991
  (49581, 555)	0.08424218838425554
  (49581, 2187)	0.14180348667063264
  (49581, 2217)	0.09535602544797335
  (49581, 4347)	0.17508214877875983
  (49581, 4629)	0.1157123083349983
  (49581, 3647)	0.087334023293812
  (49581, 4734)	0.12354122837064464
  (49581, 1977)	0.1279546327938257
  (49581, 527)	0.1247934452922504
  (49581, 2621)	0.17341357547872566
  (49581, 4458)	0.16002233459530202
  (49581, 2174)	0.18983797727912208
  (49581, 4033)	0.20100044911463438
  (49581, 341)	0.14784964476913964
  (49581, 2695)	0.1740080872946952
  (49581, 439)	0.13323526536564564
  (49581, 4980)	0.15095820717373318
  (49581, 1764)	0.15815315432712562
  (49581, 3489)	0.1519741559925848

## DataSet and DataLoaders

In [40]:
from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(
    X , y , test_size=0.2 , random_state=42
)

In [41]:
X_train.shape

(39665, 5000)

In [42]:
X_test.shape

(9917, 5000)

In [46]:
import torch
from torch.utils.data import TensorDataset , DataLoader

In [48]:
X_train = X_train.toarray()
X_test = X_test.toarray()

In [49]:
train_set = TensorDataset( # training set
    torch.from_numpy(X_train).float(),
    torch.from_numpy(y_train.values).float()


)

test_set = TensorDataset(
    torch.from_numpy(X_test).float(),
    torch.from_numpy(y_test.values).float()

)

In [50]:
train_loader = DataLoader(train_set, shuffle=True ,batch_size=64 )
test_loader = DataLoader(test_set, shuffle=True ,batch_size=64 )

## Build Our RNN

In [55]:
import torch.nn as nn
import torch.optim as optim

In [56]:
class RNN(nn.Module):
  def __init__(self , input_size , hidden_size=128 , num_layers=1):
    super().__init__()

    self.hidden_size = hidden_size
    self.num_layers = num_layers

    #RNN layer
    self.rnn = nn.RNN(input_size , hidden_size , num_layers , batch_first=True) # by using this batch-first=True we are changing the input parameters order which reduces the computation


    # fully connected layers
    self.fc = nn.Linear(hidden_size , 1)

  def forward(self , x ): # for forwad propagation
    #optional=> shape(num of layers, batch_size, hidden_layer)
    h0 = torch.zeros(self.num_layers , x.size(0) , self.hidden_size) # cause this is what happends , just to show this is written by default also it sarts from h0

    out, _ = self.rnn(x , h0)
    #1st value = hidden states of all the timestamp => (batch , seq_len , hidden size)
    #2nd value = final hidden state of the last timestamp

    out = self.fc(out[: , -1 , :]) # we just need the last hidden layer so the sequence_len given is -1
    return out

In [57]:
# creating model

input_size = X_train.shape[1]

model= RNN(input_size)

criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters())

# Training the RNN

In [62]:
# unsqueeze squeeze
epochs = 10

for epoch in range(epochs) :
  model.train()

  for Xb , yb in train_loader :
    optimizer.zero_grad()

    Xb = Xb.unsqueeze(1) # up unsqueeze and make it to 3D as in Tfidf it is in 2D, by adding a singleton direction

    outputs = model(Xb) # (batch size , 1)

    outputs = torch.sigmoid(outputs.squeeze()) #(batch_size,)=> probability

    loss = criterion(outputs, yb) # compute loss
    loss.backward() # backprop
    optimizer.step() # weights update

  print(f"epoch = {epoch+1}/{epochs} and loss = {loss.item()}")

epoch = 1/10 and loss = 0.4184163510799408
epoch = 2/10 and loss = 0.25581952929496765
epoch = 3/10 and loss = 0.14203955233097076
epoch = 4/10 and loss = 0.14735566079616547
epoch = 5/10 and loss = 0.20959055423736572
epoch = 6/10 and loss = 0.2689507305622101
epoch = 7/10 and loss = 0.284417986869812
epoch = 8/10 and loss = 0.233839213848114
epoch = 9/10 and loss = 0.15158399939537048
epoch = 10/10 and loss = 0.29837968945503235

In [63]:
# Evaluate  ( first put the model into evaluation mode)
model.eval()

with torch.no_grad():
  correct_vals= 0
  tot_vals = 0

  for Xb , yb in test_loader:
    Xb = Xb.unsqueeze(1)

    outputs = model(Xb)
    predicted = (torch.sigmoid(outputs.squeeze()) > 0.5).float()

    tot_vals += yb.size(0)
    correct_vals += (predicted == yb).sum().item()

print(f"accuracy = {correct_vals / tot_vals*100}")

accuracy = 85.23747100937784